version: '3.8'

services:
  web:
    build: .
    container_name: cornucopia-web
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cornucopia
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/app/data
    command: python main.py

  db:
    image: postgres:16
    container_name: cornucopia-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cornucopia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbscript:/docker-entrypoint-initdb.d

volumes:
  postgres_data: